/*
 * Nightbot command:
 * !editcom -ul=everyone -cd=30 !sports $(eval randomCar(); $(urlfetch json https://raw.githubusercontent.com/KDawgHonda777/KDawgHonda/main/random-sports.js);)
 */
function randomCar() {
  var cars = [
    "Itali GTO",
    "S95",
    "Pariah",
    "Banshee", 
    "Comet SR",
    "Imorgon",
    "Pathetic Easy Mode",
    "Paragon R",
    "Jugular",
    "Elegy RH8", 
    "10F Widebody", 
    "Sultan Classic",
    "Sultan RS Classic",
    "Vectre",
    "Calico GTF",
    "Feltzer",
    "Growler",
    "Neon",
    "Jester (Racecar)",
    "Elegy Retro Custom",
    "Schlagen GT",
    "8F Drafter",
    "Sentinel Classic Widebody", 
    "Massacro (Racecar)",
    "Flash GT",
    "Coquette D10",
    "9F",
    "Revolter",
    "Komoda",
    "Specter Custom",
    "Jester RR",
    "Bestia GTS",
    "Specter",
    "Cypher",
    "Raiden",
    "Sentinel Classic", 
    "Seven-70",
    "Euros",
    "Locust",
    "Comet S2",
    "Schafter V12",
    "Comet",
    "Comet Retro Custom",
    "Verlierer",
    "Carbonizzare",
    "Sultan",
    "Remus",
    "Jester Classic",
    "Coquette",
    "RT3000", 
    "GB200", 
    "Kuruma",
    "Tropos Rallye",
    "Hotring Sabre",
    "Lynx",
    "Omnis",
    "ZR350",
    "Khamelion", 
    "Drift Tampa",
    "Rapid GT",
    "Fusilade",
    "Sugoi",
    "Kuruma (Armored)",
    "Futo GTX",
    "Schwartzer",
    "Penumbra",
    "Futo",
    "Go Go Monkey Blista",
    "Blista Compact"
  ];
  var i = Math.floor(Math.random() * cars.length);
  return cars[i];
}
