/*
 * Nightbot command:
 * !editcom -ul=everyone -cd=30 !sports $(eval randomCar(); $(urlfetch json https://raw.githubusercontent.com/KDawgHonda777/KDawgHonda/main/random-sports.js);)
 */
function randomCar() {
  var cars = [
    "La Coureuse", 
    "Itali GTO Stinger TT", 
    "Itali GTO", 
    "S95",
    "Pariah",
    "Banshee", 
    "Imorgon",
    "Paragon R", 
    "Jugular", 
    "Comet SR", 
    "Pathetic Easy Mode",
    "Sultan Classic", 
    "Elegy RH8", 
    "Jester (Racecar)", 
    "10F Widebody", 
    "Sultan RS Classic",
    "Vectre",
    "Feltzer", 
    "Calico GTF",
    "Jester", 
    "Growler",
    "9F", 
    "8F Drafter", 
    "Neon",
    "Elegy Retro Custom",
    "Massacro (Racecar)", 
    "Massacro", 
    "Schlagen GT",
    "Raiden", 
    "Coquette D10", 
    "Penumbra FF", 
    "Comet", 
    "300R", 
    "Seven-70", 
    "Jester RR", 
    "Bestia GTS", 
    "Euros", 
    "Specter Custom", 
    "Specter", 
    "Flash GT", 
    "V-STR", 
    "Revolter", 
    "Komoda", 
    "Cypher", 
    "Sentinel Classic Widebody", 
    "Verlierer", 
    "Schafter V12", 
    "Comet Retro Custom", 
    "Comet S2", 
    "Sentinel Classic", 
    "Locust",
    "Sultan", 
    "Carbonizzare",
    "Coquette", 
    "Remus",
    "Jester Classic",
    "Tropos Rallye", 
    "RT3000", 
    "Lynx", 
    "Kuruma",
    "Hotring Hellfire", 
    "Hotring Sabre", 
    "Omnis", 
    "GB200", 
    "Hotring Everon", 
    "Sprunk Buffalo", 
    "ZR350",
    "Drift Tampa", 
    "Rapid GT", 
    "Khamelion", 
    "Kuruma (Armored)", 
    "Furore GT", 
    "Fusilade",
    "Sugoi",
    "Futo GTX", 
    "Schwartzer", 
    "Raptor", 
    "Futo", 
    "Penumbra",
    "Blista Compact",
    "Go Go Monkey Blista"
  ];
  var i = Math.floor(Math.random() * cars.length);
  return cars[i];
}
